version: "3"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: testfligoo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql


  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_init
    command: ["airflow", "db", "init"]
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:password@postgres:5432/testfligoo
    depends_on:
      - postgres
    volumes:
      - airflow_data:/opt/airflow

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:password@postgres:5432/testfligoo
    env_file:
      - .env
    ports:
      - "8081:8080"
    command: webserver
    volumes:
      - airflow_data:/opt/airflow
      - ./scripts:/opt/airflow/scripts
      - ./dags:/opt/airflow/dags

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:password@postgres:5432/testfligoo
    command: scheduler
    volumes:
      - airflow_data:/opt/airflow

volumes:
  postgres_data:
  airflow_data: